mydjangoapp/mydjangoapp/urls.py
import mainapp.views as mainapp
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('catalog/', mainapp.catalog, name='catalog'),

    path('catalog/category/<int:pk>/', mainapp.catalog_page, name='catalog_page'),
    # path('catalog/category/<str:slug>/', mainapp.catalog_page),
    path('catalog/course/<int:pk>/', mainapp.course_page, name='course_page'),

    path('basket/', mainapp.basket, name='basket'),

    path('admin/', admin.site.urls),
]

mydjangoapp/mainapp/models.py
from django.db import models


class SubjectCategory(models.Model):
    name = models.CharField(max_length=128)
    desc = models.TextField(blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Направление подготовки'
        verbose_name_plural = 'Направления подготовки'

class Course(models.Model):
    EASY = 'e'
    MEDIUM = 'm'
    HARD = 'h'
    LEVEL_CHOICES = (
        (EASY, 'легкий'),
        (MEDIUM, 'средний'),
        (HARD, 'продвинутый'),
    )


    category = models.ForeignKey(SubjectCategory,
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    desc = models.TextField(blank=True)
    hours = models.IntegerField(default=0)
    level = models.CharField(max_length=1, choices=LEVEL_CHOICES, default=EASY)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Курс'
        verbose_name_plural = 'Курсы'

mydjangoapp/mainapp/views.py
from django.shortcuts import render

from mainapp.models import SubjectCategory, Course


def index(request):
    return render(request, 'mainapp/index.html')


def catalog(request):
    categories = SubjectCategory.objects.all()
    context = {
        'categories': categories,
        'page_title': 'каталог'
    }

    return render(request, 'mainapp/catalog.html', context)


def basket(request):
    return render(request, 'mainapp/basket.html')


def catalog_page(request, pk):
    courses = Course.objects.filter(category_id=pk)
    context = {
        'courses': courses,
        'page_title': 'страница каталога'
    }
    return render(request, 'mainapp/catalog_page.html', context)


def course_page(request, pk):
    course = Course.objects.get(pk=pk)
    context = {
        'course': course,
        'page_title': 'страница курса'
    }
    return render(request, 'mainapp/course_page.html', context)

mydjangoapp/mainapp/templates/mainapp/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{{ page_title|default:"кпк" }}</title>
    {% block css %}
        <link rel="stylesheet" href="/static/css/main.css">
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>
<div class="main-menu">
    <ul>
        <li>
            <a href="/">Главная</a>
        </li>
        <li>
            <a href="/catalog/">Каталог</a>
        </li>
        <li>
            <a href="/basket/">Корзина</a>
        </li>
    </ul>
</div>
{% block content %}
{% endblock %}
</body>
</html>

mydjangoapp/mainapp/templates/mainapp/basket.html
{% extends 'mainapp/base.html' %}

{% block content %}
    <h1>Сюда скидывать что нужно</h1>
{% endblock %}

mydjangoapp/mainapp/templates/mainapp/catalog.html
{% extends 'mainapp/base.html' %}

{% block content %}
    <h1>Каталог</h1>
    <div class="catalog-menu">
        <ul>
            {% for item in categories %}
                <li>
                    <a href="{% url 'catalog_page' item.pk %}">
                        {{ item }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>

{% endblock %}

mydjangoapp/mainapp/templates/mainapp/catalog_page.html
{% extends 'mainapp/base.html' %}

{% block content %}
    <h1>Страница каталога</h1>
    <div class="courses-menu">
        <ul>
            {% for item in courses %}
                <li>
                    <a href="{% url 'course_page' item.pk %}">
                        {{ item }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

mydjangoapp/mainapp/templates/mainapp/course_page.html
{% extends 'mainapp/base.html' %}

{% block content %}
    <h1>Курс</h1>
    <p class="course-name">
        {{ course.name }}
    </p>
    <p class="course-level">
        уровень: {{ course.get_level_display }}
    </p>
    <p class="course-desc">
        описание: {{ course.desc }}
    </p>
    <p class="course-hours">
        часов: {{ course.hours }}
    </p>
{% endblock %}

mydjangoapp/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}

{% block content %}
    <h1>Ура, проект работает!</h1>
{% endblock %}